### ISSUE TITLE
数字小于10的时候，圆点形状有点问题

### ISSUE THREAD

**Issue by aloveric** [ChaselAn/ACBadge#1]
![screen shot 2017-04-09 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/8198881/24835443/309f0e00-1d35-11e7-8aad-abd1621f0913.png)

**Comment by ChaselAn** [comment]
已修复~
前两天有点忙，没有及时修复，对此表示抱歉。

**Comment by ChaselAn** [comment]
已修复~
前两天有点忙，没有及时修复，对此表示抱歉。

**Comment by ChaselAn** [comment]
已修复~
前两天有点忙，没有及时修复，对此表示抱歉。
感谢您的关注~

**Comment by aloveric** [comment]
效率很高啦，谢谢啊~~
