### ISSUE TITLE
Cell中长按问题

### ISSUE THREAD

**Issue by al1020119** [ChaselAn/ACBadge#2]
这边遇到一个问题，如果红点在Cell上，长按Cell或者点击Cell，红点的背景色就会消失！
目前一种方法在在解决这个问题，但是考虑全局优化处理，这种方案并不靠谱。
具体方案：
所有使用红点的Cell内部重写对应点击和长按的方法，重新设置红点的颜色。

综合讨论考虑，这种方案存在潜在的问题。
希望作者能尽快更新并修复此问题！

**Comment by ChaselAn** [comment]
不好意思回复晚了。
首先红点背景色消失的原因是因为红点也是继承自UIView的一个控件，普通的继承自UIView的空间，比如UIButton、UILabel设置背景色之后，在Cell的点击或者长按过程中，背景色都是会消失的。
其次红点只是一个控件，他的消失和显示都是由外界去控制的，他不能自己去控制自己的消失显示。
至于实现，可以遍历他的父View是否是UITableCell，这个好实现，但是出于控件的思想，感觉并没有必要去由控件本身去处理这个问题

**Comment by ChaselAn** [comment]
不好意思回复晚了。
首先红点背景色消失的原因是因为红点也是继承自UIView的一个控件，普通的继承自UIView的空间，比如UIButton、UILabel设置背景色之后，在Cell的点击或者长按过程中，背景色都是会消失的。
其次红点只是一个控件，他的消失和显示都是由外界去控制的，他不能自己去控制自己的消失显示。
至于实现，可以遍历他的父View是否是UITableCell，这个好实现，但是出于控件的思想，感觉并没有必要去由控件本身去处理这个问题。

感谢您的建议，如有其它疑问，可以一起探讨。
